"""Adiciona promo_pix em Price

Revision ID: 94d98aef8c93
Revises: b251def96920
Create Date: 2026-08-01 23:41:24.661027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d98aef8c93'
down_revision = 'b251def96920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        # server_default garante que linhas já existentes (produção não
        # reseedada ainda) recebam False em vez de falhar o ALTER TABLE por
        # violar NOT NULL sem valor.
        batch_op.add_column(sa.Column('promo_pix', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_column('promo_pix')

    # ### end Alembic commands ###
