"""Adiciona original_price e promo_valid_until em Price

Revision ID: b251def96920
Revises: 6a52c622926a
Create Date: 2026-08-01 23:14:47.944698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b251def96920'
down_revision = '6a52c622926a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('promo_valid_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_column('promo_valid_until')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
